version: "3.9"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./.env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:45432/motorshopdb?schema=public
    ports:
      - 45432:5432
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: .
    environment:
      - PORT=5000
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - postgres
    volumes:
      - ./:/app/:rw

volumes:
  dbdata:
